name: Testing from commit - v2

on: push

jobs:
  test_ubuntu:
    if: "contains(github.event.head_commit.message, 'ubuntu-latest')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -E testing -vvv
      - name: Test with pytest
        run: |
          poetry run pytest --disable-warnings -n auto -m "not vis and not long" --durations=25 --durations-min=30 --dist worksteal --cli-log-level 100

  test_windows:
    if: "contains(github.event.head_commit.message, 'windows-latest')"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -E testing -vvv
      - name: Test with pytest
        run: |
          poetry run pytest --disable-warnings -n auto -m "not vis and not long" --durations=25 --durations-min=30 --dist worksteal --cli-log-level 100

  test_macos:
    if: "contains(github.event.head_commit.message, 'macos-latest')"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -E testing -vvv
      - name: Test with pytest
        run: |
          poetry run pytest --disable-warnings -n auto -m "not vis and not long" --durations=25 --durations-min=30 --dist worksteal --cli-log-level 100